config/routes.rb
Rails.application.routes.draw do

  resources :countries

  resources :document_types

  root to: 'visitors#index'

  devise_for :users, controllers: { sessions: "user/sessions", registrations: "user/registrations" }
  
  resources :users

  resources :developer do
    member do
      post "edit_skill"
      post "edit_project"
      get "new_developer_skill"
      post "create_developer_skill"
      post "delete_developer_skill"
      get "new_developer_project"
      post "create_developer_project"
      post "delete_developer_project"
      post "developer_profile"
    end
  end  

  resources :skill

  resources :project do
    collection do
      get "developer_projects"
     end 
  end  

  resources :client

  post '/search_skills/search/', to: 'search_skills#search'


  resources :search_skills do
     member do
      post 'search'
    end
  end  

  resources :developer do
    resources :developer_has_skills
  end

  resources :developer do
    resources :developer_has_projects
  end

  resources :project do
    resources :project_has_skills
  end

end

app/models/skill.rb
class Skill < ActiveRecord::Base
 has_many :person_has_skills
 has_many :project_has_skills

 has_many :person, through: :person_has_skills

 enum skill_type: %w(Languages Frameworks Data Mobile)
 enum origin: ['Open Source', 'Unix', 'Microsoft', 'IBM', 'Apple', 'Sun']

 validates_presence_of :name, :skill_type, :origin, :documentation, :current_version, :release_date

 def self.get_person_skill(ids)
		#PersonHasSkill.joins(:skill,:person).where('skill_id in (?)', ids ).select("people.last_name")
		#skill = Skill.joins(:person_has_skills,:person).where('skills.id in (?)', ids )
		@skill.person.where('id in (?)', ids)
		@skill
	end

 def self.languages	
 	where('skill_type= ?', 0)
 end

 def self.framework
  	where('skill_type = ?',1)
  end

  def self.database
  	where('skill_type = ?',2)
  end	

  def self.mobile
  	where('skill_type = ?',3)
  end

end

app/controllers/skill_controller.rb
class SkillController < ApplicationController
  before_filter :authenticate_user!
  

  def index
  	@skills = Skill.all
  end


  def new
    @skill = Skill.new
  end


  def create
    @skill = Skill.new(secure_params)
    if @skill.save
      redirect_to skill_index_path,   :notice => "Skill Created!"
    else
      render :action => 'new'
    end
  end


  def edit
     @skill = Skill.find(params[:id])
  end

  def update
     @skill = Skill.find(params[:id])
    if @skill.update_attributes(secure_params)
      redirect_to skill_index_path, :notice => "Skill updated."
    else
      render :action => 'edit'
    end
  end

  def show
  end


  def destroy
	skill = Skill.find(params[:id])
	skill.destroy
	redirect_to skill_index_path, :notice => "Skill deleted."
  end





  def secure_params
    params.require(:skill).permit(:name, :skill_type, :origin, :documentation, :description, :current_version, :release_date)
  end




end

app/helpers/skill_helper.rb
module SkillHelper
end

app/views/skill/edit.html.erb
<div class="authform_large">
   <%= form_for(:skill, :url => skill_path(@skill.id), :html => { :method => :put, :role => 'form', :multipart => true}) do |f| %>
    <div class="col-md-12">
    	<%= devise_error_messages! %>
        <% if @skill.errors.any? %>
        <div id="error_explanation">
        <ul>
        <% @skill.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
        </div>
        <% end %>
       <h3>Create a New Skill</h3>
    </div>
  <div class="row">
    <div class="col-md-6">
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
          </div>
          <div class="form-group">
              <%= f.label :Skill_Type %> </br>
              <%= f.select(:skill_type, Skill.skill_types.keys.map {|id| [id.titleize, id]} , {:selected=> Skill.skill_types.keys[@skill[:skill_type].to_i]},{ class:  'form-control'} )  %>
          </div> 
          <div class="form-group">
              <%= f.label :Origin %> </br>
              <%= f.select(:origin, Skill.origins.keys.map {|id| [id.titleize,id]}  , {:selected=> Skill.skill_types.keys[@skill[:origin].to_i]},{ class:  'form-control'})  %>
          </div> 
           <div class="form-group">
            <%= f.label :Documentation_URL %>
            <%= f.url_field :documentation, class: 'form-control' %>
          </div> 
    </div>
    <div class="col-md-6">
           <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, rows: 3, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :Current_Version %>
            <%= f.text_field :current_version, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :Release_Date %>
            <%= f.date_field :release_date, class: 'form-control' %>
          </div>
    </div>
    <div class="col-md-12 text-right">
      <%= f.submit 'Update Skill', :class => 'btn btn-primary' %>
    </div>
  </div>
  <% end %>
</div>

app/views/skill/index.html.erb
<div class="container">
  <div class="row">
    <h3>Skills</h3>
     <div class="row text-right"><%= link_to(" + Create New Skill", new_skill_path, :method => :get, :class => 'button-xs') %></div>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Skill</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @skills.each_with_index do |skill, i| %>
            <tr>
              <th scope="row"><%= i + 1%></th>
              <td><%= skill.name %></td>
    				<td>
    				  <%= link_to("Edit", edit_skill_path(skill), :method => :get, :class => 'button-xs') %>
    				  <%= link_to("Delete", skill_path(skill), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs btn-danger') %>
    				</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/skill/new.html.erb
<div class="authform_large">
   <%= form_for(@skill, url: skill_index_path,  :method => "post",:html => { :role => 'form', :multipart => true}) do |f| %>
    <div class="col-md-12">
    	<%= devise_error_messages! %>
        <% if @skill.errors.any? %>
        <div id="error_explanation">
        <ul>
        <% @skill.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
        </div>
        <% end %>
       <h3>Create a New Skill</h3>
    </div>
  <div class="row">
    <div class="col-md-6">
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
          </div>
          <div class="form-group">
              <%= f.label :Skill_Type %> </br>
              <%= f.select(:skill_type, Skill.skill_types.keys.map {|id| [id.titleize,id]}  , {},{ class:  'form-control'})  %>
          </div> 
          <div class="form-group">
              <%= f.label :Origin %> </br>
              <%= f.select(:origin, Skill.origins.keys.map {|id| [id.titleize,id]}  , {},{ class:  'form-control'})  %>
          </div> 
           <div class="form-group">
            <%= f.label :Documentation_URL %>
            <%= f.url_field :documentation, class: 'form-control' %>
          </div>
    </div>
    <div class="col-md-6">
           <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, rows: 3, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :Current_Version %>
            <%= f.text_field :current_version, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :Release_Date %>
            <%= f.date_field :release_date, class: 'form-control' %>
          </div>
    </div>
    <div class="col-md-12 text-right">
      <%= f.submit 'Create Skill', :class => 'btn btn-primary' %>
    </div>
  </div>
  <% end %>
</div>

app/views/skill/show.html.erb
<h1>Skill#show</h1>
<p>Find me in app/views/skill/show.html.erb</p>