config/routes.rb
Rails.application.routes.draw do

  resources :countries

  resources :document_types

  root to: 'visitors#index'

  devise_for :users, controllers: { sessions: "user/sessions", registrations: "user/registrations" }
  
  resources :users

  resources :developer do
    member do
      post "edit_skill"
      post "edit_project"
      get "new_developer_skill"
      post "create_developer_skill"
      post "delete_developer_skill"
      get "new_developer_project"
      post "create_developer_project"
      post "delete_developer_project"
      post "developer_profile"
    end
  end  

  resources :skill

  resources :project do
    collection do
      get "developer_projects"
     end 
  end  

  resources :client

  post '/search_skills/search/', to: 'search_skills#search'


  resources :search_skills do
     member do
      post 'search'
    end
  end  

  resources :developer do
    resources :developer_has_skills
  end

  resources :developer do
    resources :developer_has_projects
  end

  resources :project do
    resources :project_has_skills
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :projects
	


	validates_presence_of :name, :description
end

app/controllers/client_controller.rb
class ClientController < ApplicationController
  before_filter :authenticate_user!


  def index
  	@clients = Client.all
  end


  def new
    @client = Client.new
  end


  def create
    @client = Client.new(secure_params)
    if @client.save
      redirect_to client_index_path,  :notice => "Client Created!"
    else
      render :action => 'new'
    end
  end


  def edit
  	@client = Client.find(params[:id])
  end


  def update
  	 @client = Client.find(params[:id])
    if @client.update_attributes(secure_params)
      redirect_to client_index_path, :notice => "Client updated."
    else
      render :action => 'edit'
    end
  end


  def destroy
	client = Client.find(params[:id])
	client.destroy
	redirect_to client_index_path, :notice => "Client deleted."
  end


  def show
  end


  def secure_params
    params.require(:client).permit(:name, :description)
  end

end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/client/edit.html.erb
<div class="authform_large">
   <%= form_for(:client, url: client_path(@client.id),   :html => { :method => :put, :role => 'form', :multipart => true}) do |f| %>
    <div class="col-md-12">
    	<%= devise_error_messages! %>
        <% if @client.errors.any? %>
        <div id="error_explanation">
        <ul>
        <% @client.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
        </div>
        <% end %>
       <h3>Edit a New Client</h3>
    </div>
  <div class="row">
    <div class="col-md-12">
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
          </div>
           <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, rows: 8, class: 'form-control' %>
          </div>      
    </div>
    <div class="col-md-12 text-right">
      <%= f.submit 'Update Client', :class => 'btn btn-primary' %>
    </div>
  </div>
  <% end %>
</div>

app/views/client/index.html.erb
<div class="container">
  <div class="row">
    <h3>Clients</h3>
     <div class="row text-right"><%= link_to(" + Create New Client", new_client_path, :method => :get, :class => 'button-xs') %></div>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
         <tr>
          <th>#</th>
          <th>Client</th>
          <th>Actions</th>
         </tr>
        </thead>
        <tbody>
          <% @clients.each_with_index do |client,i| %>
            <tr>
              <th scope="row"><%= i + 1%></th>
              <td>
  					<%= client.name %> 
    				</td>
    				<td>
    				  <%= link_to("Edit", edit_client_path(client), :method => :get, :class => 'button-xs') %>
    				  <%= link_to("Delete", client_path(client), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs btn-danger') %>
    				</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/client/new.html.erb
<div class="authform_large">
   <%= form_for(@client, url: client_index_path,  :method => "post",:html => { :role => 'form', :multipart => true}) do |f| %>
    <div class="col-md-12">
    	<%= devise_error_messages! %>
        <% if @client.errors.any? %>
        <div id="error_explanation">
        <ul>
        <% @client.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
        </div>
        <% end %>
       <h3>Create a New Client</h3>
    </div>
  <div class="row">
    <div class="col-md-12">
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
          </div>
           <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, rows: 8, class: 'form-control' %>
          </div>      
    </div>
    <div class="col-md-12 text-right">
      <%= f.submit 'Create Client', :class => 'btn btn-primary' %>
    </div>
  </div>
  <% end %>
</div>

app/views/client/show.html.erb
<h1>Client#show</h1>
<p>Find me in app/views/client/show.html.erb</p>