config/routes.rb
Rails.application.routes.draw do

  resources :countries

  resources :document_types

  root to: 'visitors#index'

  devise_for :users, controllers: { sessions: "user/sessions", registrations: "user/registrations" }
  
  resources :users

  resources :developer do
    member do
      post "edit_skill"
      post "edit_project"
      get "new_developer_skill"
      post "create_developer_skill"
      post "delete_developer_skill"
      get "new_developer_project"
      post "create_developer_project"
      post "delete_developer_project"
      post "developer_profile"
    end
  end  

  resources :skill

  resources :project do
    collection do
      get "developer_projects"
     end 
  end  

  resources :client

  post '/search_skills/search/', to: 'search_skills#search'


  resources :search_skills do
     member do
      post 'search'
    end
  end  

  resources :developer do
    resources :developer_has_skills
  end

  resources :developer do
    resources :developer_has_projects
  end

  resources :project do
    resources :project_has_skills
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :client
  has_many :project_has_skills
  has_many :person_has_projects

  validates_presence_of :name, :description, :start_date, :website, :github

  def current_project
  	  Project.where("id = (?) AND finish_date = (?)",self.id, nil).empty? ? true : false
  end


end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  before_filter :authenticate_user!
  

  def index
  	@projects = Project.all
  end


  def new
     @project = Project.new
  end


  def create
	  @project = Project.new(secure_params)
    @project.client_id = params[:client_id]
	  if @project.save
	    redirect_to project_index_path, :notice => "Project Created!"
	  else
      render :action => 'new'
	  end
  end


  def edit
    @project = Project.find(params[:id])
  end


  def update
  	 @project = Project.find(params[:id])
     @project.client_id = params[:client_id]
    if @project.update_attributes(secure_params)
      redirect_to project_index_path, :notice => "Project updated."
    else
      render :action => 'edit'
    end
  end


  def destroy
	project = Project.find(params[:id])
	project.destroy
	redirect_to project_index_path, :notice => "Project deleted."
  end

  def developer_projects
    @developers = Person.all
    month_range =   Date.today.beginning_of_year..Date.today.end_of_year
    generate_month = month_range.map(&:beginning_of_month)
    @month_range = generate_month.map { |dates| dates.strftime("%b") }.uniq
    @total_billables = PersonHasProject.total_billables
    @total_projects = PersonHasProject.total_projected
    @total_bench = PersonHasProject.total_bench
  end  


  def secure_params
    params.require(:project).permit(:name, :description, :client_id, :start_date, :finish_date ,:website, :github)
  end


end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/project/developer_projects.html.erb
<h2>Projects Information</h2>
<table class="table table-bordered">
<thead>
<th>Team Member</th>	
	<% @month_range.each do | month|%>
<th><%= month%></th>
	<%end%>
</thead>	
<tbody>	
<tr>
<td>Total Billable</td>

<%@total_billables.each do |total|%>
	<td><%=total.second%></td>
<%end%>
</tr>
<tr>
<td>Total Project (include yellow)</td>
<%@total_projects.each do |total|%>
	<td><%=total.second%></td>
<%end%>
</tr>
<tr>
<td>Bench</td>	
<%@total_bench.each do |total|%>
	<td><%=total.second%></td>
<%end%>
</tr>	
<tr>
<td colspan="13">&nbsp;</td>	
</tr>
	<%@developers.each do |person| %>
      <tr><td><%= link_to person.full_name, developer_path(person) %></td>
	    <% person.developer_in_project.each do |a|%>
			<td class ="<%= fill_background(a[1].blank? ? a[1] : a[1].first[:developer_condition])%>">
			<%=a[1].blank? ? "" : link_to(a[1].first.project.name,"javascript:",{data:{ toggle: "tooltip", placement: "top", 'original-title'=> a[1].first.developer_condition.titleize}})%></td>
	    <%end%>	
	  </tr>  	
   <%end%>

</tbody>
</table>	

app/views/project/edit.html.erb
<div class="authform_large">
   <%= form_for(@project, url: project_path(@project.id),  :html => { :method => :put, :role => 'form', :multipart => true}) do |f| %>
    <div class="col-md-12">
      <%= devise_error_messages! %>
      <% if @project.errors.any? %>
      <div id="error_explanation">
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
      </div>
      <% end %>
       <h3>Create a New Project</h3>
    </div>
  <div class="row">
    <div class="col-md-6">
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
          </div>
           <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, rows: 12, class: 'form-control' %>
          </div>
    </div>
    <div class="col-md-6">
          <div class="form-group">
            <%= f.label :Client %>
            <%= select_tag :client_id, options_for_select(Client.all.collect {|u| [ u.name, u.id ] }, @project.client_id),  class: 'form-control'%>
          </div>  
    	   <div class="form-group">
            <%= f.label :Start_Date %>
            <%= f.date_field :start_date, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :Finish_Date %>
            <%= f.date_field :finish_date, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :Website %>
            <%= f.url_field :website, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :Github_Repository %>
            <%= f.url_field :github, class: 'form-control' %>
          </div>
    </div>
    <div class="col-md-12">
      <%= f.submit 'Update Project', :class => 'btn btn-primary btn-lg btn-block' %>
    </div>
  </div>
  <% end %>
</div>

app/views/project/index.html.erb
<div class="container">
  <div class="row">
    <h3>Projects</h3>
     <div class="row text-right"><%= link_to(" + Create New Project", new_project_path, :method => :get, :class => 'button-xs') %></div>
     <div class="row table-responsive">
      <table class="table table-striped">
        <tr>
          <th>#</th>
          <th>Project</th>
          <th>Actions</th>
        </tr>
        <tbody>
          <% @projects.each_with_index do |project, i| %>
            <tr>
               <th scope="row"><%= i + 1 %></th>
              <td>
      					<%= project.name %> <span class="label label-primary label-project">Developers <span class="badge"><%= project.person_has_projects.current_projects.count%></span></span>
    				</td>
    				<td>
              <%= link_to("Manage Skills", project_project_has_skills_path(project), :class => 'button-xs btn-success') %>
    				  <%= link_to("Edit", edit_project_path(project), :method => :get, :class => 'button-xs') %>
    				  <%= link_to("Delete", project_path(project), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs btn-danger') %>
    				</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/project/new.html.erb
<div class="authform_large">
   <%= form_for(@project, url: project_index_path,  :method => "post",:html => { :role => 'form', :multipart => true}) do |f| %>
    <div class="col-md-12">
    	<%= devise_error_messages! %>
        <% if @project.errors.any? %>
        <div id="error_explanation">
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
        </div>
        <% end %>
       <h3>Create a New Project</h3>
    </div>
  <div class="row">
    <div class="col-md-6">
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
          </div>
           <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, rows: 12, class: 'form-control' %>
          </div>          
    </div>
    <div class="col-md-6">
          <div class="form-group">
            <%= f.label :Client %>
            <%= select_tag :client_id, options_for_select(Client.all.collect {|u| [ u.name, u.id ] }),  class: 'form-control'%>
          </div>    
    	   <div class="form-group">
            <%= f.label :Start_Date %>
            <%= f.date_field :start_date, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :Finish_Date %>
            <%= f.date_field :finish_date, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :Website %>
            <%= f.url_field :website, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :Github_Repository %>
            <%= f.url_field :github, class: 'form-control' %>
          </div>
    </div>
    <div class="col-md-12">
      <%= f.submit 'Create Project', :class => 'btn btn-primary btn-lg btn-block' %>
    </div>
  </div>
  <% end %>
</div>

app/views/project/show.html.erb
<h1>Project#show</h1>
<p>Find me in app/views/project/show.html.erb</p>