config/routes.rb
Rails.application.routes.draw do

  resources :countries

  resources :document_types

  root to: 'visitors#index'

  devise_for :users, controllers: { sessions: "user/sessions", registrations: "user/registrations" }
  
  resources :users

  resources :developer do
    member do
      post "edit_skill"
      post "edit_project"
      get "new_developer_skill"
      post "create_developer_skill"
      post "delete_developer_skill"
      get "new_developer_project"
      post "create_developer_project"
      post "delete_developer_project"
      post "developer_profile"
    end
  end  

  resources :skill

  resources :project do
    collection do
      get "developer_projects"
     end 
  end  

  resources :client

  post '/search_skills/search/', to: 'search_skills#search'


  resources :search_skills do
     member do
      post 'search'
    end
  end  

  resources :developer do
    resources :developer_has_skills
  end

  resources :developer do
    resources :developer_has_projects
  end

  resources :project do
    resources :project_has_skills
  end

end

app/models/project_has_skill.rb
class ProjectHasSkill < ActiveRecord::Base
  belongs_to :project
  belongs_to :skill
  
  validates_presence_of :note

	def self.list_project_skills(proj)
		ProjectHasSkill.where("project_id = ?" , proj)
	end

	def self.list_of_valid_skills(proj_object)
		not_in = []
		proj_object.each do |dev_skill|
			not_in.push(dev_skill.skill_id)
		end
			
		unless not_in.first.blank?
		     Skill.where.not('id in (?)', not_in )
		else
			 Skill.all
		end
	end

end

app/controllers/project_has_skills_controller.rb
class ProjectHasSkillsController < ApplicationController
  before_filter :authenticate_user!

  def index
  	 @project = Project.find(params[:project_id])
     @project_skills = ProjectHasSkill.list_project_skills(params[:project_id])
     @project_assigned_skills = ProjectHasSkill.list_of_valid_skills(@project_skills)
  end


  def edit
     @project = Project.find(params[:project_id])
     @project_skill = ProjectHasSkill.find(params[:id])

  end

  def new
     @project = Project.find(params[:project_id])
     @project_skills_list = ProjectHasSkill.list_project_skills(params[:project_id])
     @project_assigned_skills = ProjectHasSkill.list_of_valid_skills(@project_skills_list)
     @project_skill = ProjectHasSkill.new
  end

  def show
  end

  def create
    @project_skill = ProjectHasSkill.new(secure_params)
    @project_skill.project_id = params[:project_id]
    if @project_skill.save
      redirect_to project_project_has_skills_path,   :notice => "Skill Association Created!"
    else
      @project = Project.find(params[:project_id])
      @project_skills_list = ProjectHasSkill.list_project_skills(params[:project_id])
      @project_assigned_skills = ProjectHasSkill.list_of_valid_skills(@project_skills_list)
      render :action => 'new'
    end
  end

  def update
     @project_skill = ProjectHasSkill.find(params[:id])
    if @project_skill.update_attributes(secure_params)
      redirect_to project_project_has_skills_path, :notice => "Skill Association updated."
    else
      @project = Project.find(params[:project_id])
      render :action => 'edit'
    end
  end


  def destroy
    project_skill = ProjectHasSkill.find(params[:id])
    project_skill.destroy
    redirect_to project_project_has_skills_path, :notice => "Association deleted."
  end



  def secure_params
    params.require(:project_has_skill).permit(:project_id, :skill_id, :note)
  end

end

app/helpers/project_has_skills_helper.rb
module ProjectHasSkillsHelper
end

app/views/project_has_skills/edit.html.erb
<div class="authform_large">
   <%= form_for(@project_skill, url: project_project_has_skill_path(@project.id, @project_skill.id), :html => { :method => :put, :role => 'form', :multipart => true}) do |f| %>
    <div class="col-md-12">
    	<%= devise_error_messages! %>
          <% if @project_skill.errors.any? %>
          <div id="error_explanation">
          <ul>
          <% @project_skill.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
          </div>
          <% end %>
       <h3>Associate Skill to <%= @project.name.to_s  %> Project</h3>
    </div>
    <div class="row">
      <div class="col-md-12">
            <div class="form-group">
                <%= f.label :Skill %> </br>
                <%= f.select(:skill_id, options_for_select(Skill.all.collect {|u| [ u.name, u.id ] }) , {},{ class:  'form-control', :disabled => true})  %>
            </div> 
             <div class="form-group">
              <%= f.label :Additional_notes %>
              <%= f.text_area :note, rows: 5, class: 'form-control' %>
            </div>     
      </div>
      <div class="col-md-12">
        <%= f.submit 'Associate Skill', :class => 'btn btn-primary btn-lg btn-block' %>
      </div>
    </div>
  <% end %>
</div>

app/views/project_has_skills/index.html.erb
<div class="container">
  <div class="row">
    <h3><%=  @project.name.to_s %> Skills</h3>
     <% unless@project_assigned_skills.first.blank?  %>
         <h6><%= link_to(" + Associate New Skill ", new_project_project_has_skill_path, :method => :get, :class => 'button-xs') %></h6>
     <% else %>
        <h6>You already assigned all the available skills to <%=  @project.name.to_s  %> </h6>
     <%end%>
    <div class="column">
      <table class="table">
        <tbody>
          <% @project_skills.each do |project_skill| %>
            <tr>
              <td>
  					<%= project_skill.skill.name.to_s %> 
    				  </td>
      				<td>
      				  <%= link_to("Edit", edit_project_project_has_skill_path(project_skill.project_id,project_skill ), :method => :get, :class => 'button-xs') %>
      				  <%= link_to("Delete", project_project_has_skill_path(project_skill.project_id,project_skill), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') %>
      				</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/project_has_skills/new.html.erb
<div class="authform_large">
   <%= form_for(@project_skill, url: project_project_has_skills_path,  :method => "post",:html => { :role => 'form', :multipart => true}) do |f| %>
    <div class="col-md-12">
    	<%= devise_error_messages! %>
          <% if @project_skill.errors.any? %>
          <div id="error_explanation">
          <ul>
          <% @project_skill.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
          </div>
          <% end %>
       <h3>Associate Skill to <%= @project.name.to_s  %> Project</h3>
    </div>
    <div class="row">
      <div class="col-md-12">
            <div class="form-group">
                <%= f.label :Skill %> </br>
                <%= f.select(:skill_id, options_for_select(@project_assigned_skills.collect {|u| [ u.name, u.id ] }) , {},{ class:  'form-control'})  %>
            </div> 
             <div class="form-group">
              <%= f.label :Additional_notes %>
              <%= f.text_area :note, rows: 5, class: 'form-control' %>
            </div>     
      </div>
      <div class="col-md-12">
        <%= f.submit 'Associate Skill', :class => 'btn btn-primary btn-lg btn-block' %>
      </div>
    </div>
  <% end %>
</div>

app/views/project_has_skills/show.html.erb
<h1>ProjectHasSkills#show</h1>
<p>Find me in app/views/project_has_skills/show.html.erb</p>